nelmio_api_doc:
    documentation:
        info:
            title: API test ex
            description: Test ex
            version: 0.0.1
        tags:
            - name: "Guest"
              description: "Гость"
    areas:
        default:
            path_patterns:
                - ^/api/
