version: '3.8'

services:
  shop-php-fpm:
    container_name: shop-php-fpm
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: docker
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/shop

  shop-nginx:
    image: nginx:latest
    container_name: shop-nginx
    restart: always
    depends_on:
      - shop-php-fpm
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/shop
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shop}
      POSTGRES_USER: ${POSTGRES_USER:-shop}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"

volumes:
  database_data:
